let data = [
  (Ahafo = [
    "Abuom",
    "Achirensua",
    "Adrobaa",
    "Ahantamo",
    "Akokobenomnsu",
    "Akrodie",
    "Amanfrom",
    "Ankaase",
    "Ankonsia",
    "Anwiam",
    "Asawenso",
    "Asuboi",
    "Asukese",
    "Asumura",
    "Atom",
    "Atta ne Atta",
    "Ayomso",
    "Bechem",
    "Bediako",
    "Biaso",
    "Boaso",
    "Bomaa",
    "Bredi",
    "Breme",
    "Brosankro",
    "Camp No.1",
    "Dadiesoaba",
    "Derma",
    "Dominase",
    "Duayaw Nkwanta",
    "Dwomo",
    "Fawohoyeden",
    "GOASO",
    "Hwidiem",
    "Jeinsuso",
    "Kawteigo",
    "Kenyasi",
    "Kenyasi Mohu",
    "Konkontreso",
    "Kukuom",
    "Kwapong",
    "Mansin",
    "Mehame",
    "Mim",
    "Mim Mohu",
    "Mpamase",
    "Nkaseim",
    "Noberkaw",
    "Ntotroso",
    "Okrakrom",
    "Pafo",
    "Pomaakrom",
    "Sanbasi",
    "Siana",
    "Sienchem",
    "Sikafrebogya",
    "Sireso",
    "Subriso",
    "Susuanso",
    "Tanoano",
    "Tanoso",
    "Techimantia",
    "Terchire",
    "Twabidi No.1",
    "Twabidi No.2",
    "Wamahinso",
    "Yamensakrom",
    "Yamfo",
  ]),
  (Ashanti = [
    "Abaase",
    "Abesewa",
    "Abira (Atwima)",
    "Abira (Kwabre)",
    "Aboabo No.1",
    "Aboabogya",
    "Aboaboso",
    "Abodom",
    "Abofour",
    "Abofrim",
    "Aboma",
    "Abonu",
    "Abori",
    "Abosamso",
    "Abotang",
    "Abrofirim",
    "Abuakwa",
    "Abuakwaa",
    "Abwantem",
    "Achiase",
    "Achinakrom",
    "Adankwamu",
    "Adansi Asokwa",
    "Adansi Praso",
    "Adanwomase",
    "Adiembra",
    "Adomfe",
    "Adonso",
    "Adugyama",
    "Adujanso",
    "Adumanu",
    "Adwafo",
    "Aframso (Chirade)",
    "Aframso (Chirimfa)",
    "Aframso (Kyekyebon)",
    "Afrancho",
    "Afrante",
    "Afrantwo",
    "Agogo",
    "Agona",
    "Ahansonyewodea",
    "Ahenkro",
    "Ahinsan",
    "Ahodwo",
    "Ahwerewa",
    "Ahwerewam",
    "Ahwiaa",
    "Ahwiren",
    "Ahyireso",
    "Ajumakese",
    "Akotaa",
    "Akrantiebesa",
    "Akrofuom",
    "Akrokeri",
    "Akrokyere",
    "Akropong",
    "Akrowi",
    "Akuakrom",
    "Akumadan",
    "Akutuase",
    "Akwanserem",
    "Akyerekyekrom",
    "Amakye Bare",
    "Amanchia",
    "Amenso",
    "Amentia",
    "Amoako",
    "Amoamang",
    "Amoawi",
    "Amormoso",
    "Amponya",
    "Ampunyase",
    "Amudurasi",
    "Aniamoa",
    "Ankaase (AK)",
    "Ankaase (Bekwai)",
    "Ankaase (B.Freho)",
    "Ankam",
    "Antoa",
    "Antoakrom",
    "Anumso",
    "Anhwiaso",
    "Anwiafutu",
    "Anwiankwanta",
    "Anwiaso",
    "Anyanso",
    "Anyinamso Nos.1&2",
    "Anyinasu",
    "Anyinasuso",
    "Anyinofi",
    "Apagya",
    "Apapaso",
    "Apiadu",
    "Asaam",
    "Asakraka",
    "Asaman",
    "Asamang (Bekwai)",
    "Asamang (Sekyere)",
    "Asamankama",
    "Asankari",
    "Asarekrom",
    "Asempanaye",
    "Asisiriwa",
    "Asiwa",
    "Asokore",
    "Asokore Mampong",
    "Asokwa",
    "Asonomaso",
    "Asotwe",
    "Asuboi",
    "Asubon",
    "Asubua",
    "Asubuasu",
    "Asuhyiae",
    "Asumen",
    "Asuoso",
    "Atasi",
    "Ataase Nkwanta",
    "Atasomanso",
    "Atobiasi",
    "Atonsu",
    "Atonsuagya",
    "Atta Akura",
    "Attakrom",
    "Atunso",
    "Aworoso",
    "Babaso",
    "Balana",
    "Banka",
    "Bankame",
    "Banko",
    "Banso (Akim)",
    "Banso (B.Freho)",
    "Bantama",
    "Barekese",
    "Barekuma",
    "Bedomase",
    "Begroase",
    "Bekwai",
    "Bemi",
    "Benim",
    "Bepoase",
    "Beposo (Bosomtwe)",
    "Beposo (Sekyere)",
    "Berem",
    "Besease (Amansie)",
    "Besease (Ejisu)",
    "Besoro",
    "Betenase",
    "Betiako",
    "Biemso No.1",
    "Bipoa",
    "Boamang",
    "Boanim",
    "Boankra",
    "Bobriase",
    "Bodomase",
    "Bodwesango",
    "Bogyawe",
    "Bomfa",
    "Bompata",
    "Boni",
    "Bonsaaso",
    "Bonteso",
    "Bontomruso",
    "Bonwire",
    "Bosafo",
    "Bosomkyekye",
    "Bowohomoden",
    "Brahabebome",
    "Bremang",
    "Brodekwano",
    "Brofoyedru (Adansi)",
    "Brofoyedru (Offinso)",
    "Bronikrom",
    "Bunaso",
    "Bunyum",
    "Buoho",
    "Daban",
    "Dampong",
    "Danso",
    "Darko",
    "Darso",
    "Datano",
    "Densubon",
    "Denyase",
    "Didaso",
    "Domase",
    "Dome",
    "Dome Beposo",
    "Domeabra (AA)",
    "Domeabra (Sekyere)",
    "Domi Keniago",
    "Domiabra",
    "Dominase",
    "Dompoase",
    "Dotiem",
    "Drabon",
    "Drobonso",
    "Dukusen",
    "Dumienu",
    "Dunyankwanta",
    "Dwinyama",
    "Dwoamin",
    "Ebiram",
    "Eduadin",
    "Eduaniyede",
    "Edubiase",
    "Edumasa",
    "Edwenase",
    "Effiduase",
    "Ejian",
    "Ejisu",
    "Ejura",
    "Esaase (B.Freho)",
    "Esaase (Juaben)",
    "Esaso",
    "Esiana",
    "Essumeja",
    "Essuowin",
    "Etia",
    "Fankyenebra",
    "Fawoade",
    "Fawoman",
    "Fenaso",
    "Feyiasi",
    "Fiankoma",
    "Foase",
    "Fomena",
    "Freboye Nos.1&2",
    "Fereso No.2",
    "Fufuo",
    "Fumisua",
    "Fumso",
    "Hemang",
    "Hia",
    "Hiakwasi",
    "Hiawoanwu",
    "Hiawu Besease",
    "Hun",
    "Hwidiem",
    "Hwereso",
    "Jachi",
    "Jacobu",
    "Jadiako",
    "Jamasi",
    "Jiasi",
    "Jimiso Kakraba",
    "Juaben",
    "Juahaw",
    "Juansa",
    "Juaso",
    "Kankanfriasi",
    "Kasaam",
    "Kasei",
    "Katie",
    "Kenseri",
    "Kenyase",
    "Kobreso",
    "Kodie",
    "Kofiase",
    "Kojo Nkwanta",
    "Kojoetraco",
    "Kokoben",
    "Kokodie, Kokofu",
    "Kokote",
    "Kokotro",
    "Komeso",
    "Kona",
    "Koniyaw",
    "Konkori",
    "Konongo",
    "Konongo-Odumase",
    "Kotokuom",
    "Krofa",
    "Kubease",
    "Kubekro",
    "KUMASI",
    "Kumawu",
    "Kumpese",
    "Kunso",
    "Kuntanase",
    "Kwadaso",
    "Kwamang (AK)",
    "Kwamang (Sekyere)",
    "Kwame Dwuma Sreso",
    "Kwamekyemkrom",
    "Kwamo",
    "Kwapeni",
    "Kwaso",
    "Kyebi",
    "Kyekyebon",
    "Kyekyewere (AK)",
    "Kyekyewere (AM)",
    "Kyenkyenase",
    "Kyereyaaso",
    "Kyeyiase",
    "Kyiremfaso",
    "Mabang",
    "Mampong",
    "Mampong  Akrofoso",
    "Mamponteng",
    "Manesuso",
    "Manfo (AA)",
    "Manfo (Amansie)",
    "Manhyia",
    "Mankranso",
    "Manso Adubia",
    "Manso Akropong",
    "Manso Nkwanta",
    "Manukrom",
    "Mem",
    "Mensonso",
    "Meyenwaikosimeyie",
    "Mfensi",
    "Mile 9",
    "Mile 14",
    "Miminaso Nos.1&2",
    "Miradani",
    "Maluu",
    "Moseaso",
    "Mpantuase",
    "Mpatuam",
    "Mpesaso",
    "Mpesetia",
    "Mpobi",
    "Naama",
    "Namong",
    "Nerebehi",
    "New Akrofuom",
    "New Ayaase",
    "New Edubiase",
    "New Koforidua",
    "Nimreso",
    "Nkaneku",
    "Nkawie",
    "Nkawie Kuma",
    "Nkawie Panin",
    "Nkenkaasu",
    "Nkwanta",
    "Nkwantakese",
    "Nkwatem",
    "Nsiakrom",
    "Nsonyameye",
    "Nsuaem Nos.1&2",
    "Nsuontam",
    "Nsuta",
    "Nsuta (AA)",
    "Nsutam",
    "Ntobroso",
    "Ntonso",
    "Nubuom",
    "Nukwasa",
    "Nwineso No.1",
    "Nyameadom",
    "Nyamiadum",
    "Nyameani",
    "Nyamebekyere",
    "Nyankyerenease",
    "Nyinahin",
    "Obo",
    "Obogu",
    "Obuasi",
    "Odaho",
    "Odumase",
    "Odumasi",
    "Offe",
    "Offinso",
    "Ofoase",
    "Ofoase Kokoben",
    "Oforikrom",
    "Old Tafo",
    "Onyimso",
    "Owabi",
    "Owuokrom",
    "Owusukrom",
    "Oyoko",
    "Parkoso",
    "Pankronu",
    "Pasaro",
    "Patakro",
    "Patase",
    "Patriensa",
    "Patrikrom",
    "Pechereche",
    "Pechi",
    "Pemenasi",
    "Penteng",
    "Piase",
    "Pipiiso",
    "Poanu",
    "Pokukrom",
    "Pomposo",
    "Pra River",
    "Praaso",
    "Saabuso",
    "Saakrom",
    "Sabonline",
    "Sabronum",
    "Sampreso",
    "Sasebonso",
    "Sataso",
    "Sawia",
    "Sedi",
    "Sekyedumase",
    "Senfi",
    "Seniagya",
    "Senkye",
    "Sepasi",
    "Sikaman",
    "Soko",
    "Sokoben",
    "Sraneso No.1",
    "Sreso Timpom",
    "Suame",
    "Sukuumu",
    "Sumiso",
    "Suntreso",
    "Surukrom",
    "Swedru",
    "Trabuom",
    "Tafo",
    "Takorase",
    "Tano Odumase",
    "Tano Odumasi",
    "Tanokwaem",
    "Teacherkrom",
    "Tebeso No.1",
    "Tebeso No.2",
    "Tepa",
    "Tetrem",
    "Toase",
    "Tontokrom",
    "Trede",
    "Tutuka",
    "Twedie",
    "Tweapease",
    "Unya",
    "Wamasi",
    "Watreso",
    "Wawase",
    "Wiamuasi",
    "Wiawso",
    "Wiawso",
    "Winiso Akrampa",
    "Woraso (Mampong)",
    "Woraso (Kumawu)",
    "Wurapong",
    "Yabi",
    "Yireso",
    "Yoribon",
    "Yuabra",
  ]),
  (Bono = [
    "Aboabo Nos.1-4",
    "Aboabo",
    "Abuokrom",
    "Adadiem",
    "Adamsu",
    "Adomase",
    "Agbelikame No.2",
    "Ahomansia",
    "Ahwene",
    "Ahyiayem",
    "Ayaayo",
    "Akanyakrom",
    "Akete",
    "Akontanim",
    "Akrobi",
    "Akroforo",
    "Amasu",
    "Amomaso",
    "Amponsakrom",
    "Antwirifo",
    "Asempanaye",
    "Asikasu",
    "Asuano",
    "Asuokor",
    "Asunsu",
    "Asuofiri",
    "Asuogya",
    "Atronie",
    "Atuna (West)",
    "Atuna (East)",
    "Awisa",
    "Ayakomaso",
    "Ayimom",
    "Baano",
    "Babianiha",
    "Badu",
    "Banda Ahenkro",
    "Bator",
    "Bepoase",
    "Beposo",
    "Berekum",
    "Biadan",
    "Biama",
    "Biema",
    "Boase",
    "Bodaa",
    "Bofie",
    "Buoku",
    "Bongase",
    "Borfuakura",
    "Bosuaba",
    "Branam",
    "Brewohodi",
    "Brodi",
    "Brohani",
    "Bui",
    "Buko",
    "Buku",
    "Centreso",
    "Chiraa",
    "Dawiri",
    "Debibi",
    "Degedege",
    "Diabakrom",
    "Dorbor",
    "Dokokyina",
    "Dompofie",
    "Dormaa Ahenkro",
    "Dormaa Akwamu",
    "Drobo",
    "Droboso",
    "Duabone No.2",
    "Duadaso",
    "Dumasua",
    "Dumoli",
    "Dwenem",
    "Fetentaa",
    "Feteyano",
    "Fiapre",
    "Goka",
    "Gonasua",
    "Gradaw",
    "Hani",
    "Jamera",
    "Jankru",
    "Jankufa",
    "Japekrom",
    "Jenjemireja",
    "Jensoso",
    "Jinijini",
    "Jinini",
    "Kaabre",
    "Kabile",
    "Kasa",
    "Kofiasua",
    "Kojee",
    "Kokoa",
    "Kokorasua",
    "Kontrajeso",
    "Korase",
    "Koraso",
    "Kotuo",
    "Krachikrom",
    "Krakrom",
    "Kusiasi",
    "Kutre",
    "Kwakuanya",
    "Kwameasua",
    "Kwatire",
    "Kyeremasu",
    "Kyiribogya",
    "Laura",
    "Mallamkrom",
    "Mantukwa",
    "Masu",
    "Mayera",
    "Mempeasem",
    "Menji",
    "Miremano",
    "Morle",
    "Mpuasu",
    "Namasa",
    "Namasua",
    "Nasana",
    "Nchiraa",
    "New Drobo",
    "Njau",
    "Nkonsia",
    "Nkoran Kwagya",
    "Nkrankwanta",
    "Nsawkaw",
    "Nsoatre",
    "Nsuoano",
    "Ntereso",
    "Ntinsri",
    "Ntoasua",
    "Nwereme",
    "Nyamefie",
    "Nyire",
    "Odumase",
    "Oforikrom",
    "Okirakrom",
    "Old Drobo",
    "Pobire",
    "Sabiye",
    "Samba",
    "Sampa",
    "Sanbasi",
    "Sebreni",
    "Seketia",
    "Seikwa",
    "Senikrom",
    "Sromani",
    "Subinso No.1",
    "Subinso No.2",
    "SUNYANI",
    "Tainano",
    "Tainso",
    "Tromeso",
    "Tronang",
    "Twumkrom",
    "Wamanafo",
    "Wamfie",
    "Wenchi",
    "Wewa",
    "Wurompon",
    "Yaakrom",
    "Yaa Mensa",
    "Yabraso",
    "Yawkrom",
    "Yoyoano",
    "Zobo",
  ]),
  (Bono_East = [
    "Abama",
    "Abease",
    "Aboabo",
    "Abontiem",
    "Abuo",
    "Afrefreso",
    "Agosa",
    "Agyina",
    "Ahotor",
    "Ayerede",
    "Akisimasu",
    "Akokoa",
    "Akrofonso",
    "Akuma",
    "Akumsa Domase",
    "Amangoase",
    "Amantin",
    "Amoma",
    "Ampedu",
    "Ampoma",
    "Anyima",
    "Apesika",
    "Asuano",
    "Asueyi",
    "Atebubu",
    "Atrensu",
    "Atta Akuraa",
    "Aworowa",
    "Awurata",
    "Baamiri",
    "Baniantwe",
    "Bankama",
    "Bantama",
    "Barache",
    "Bassa",
    "Bewele",
    "Besedan",
    "Bianhyew",
    "Boabeng",
    "Bodom",
    "Bonsu",
    "Bolga Nkwanta",
    "Bolga Village",
    "Bompoi",
    "Bonte",
    "Bredi No.1",
    "Bresuoano",
    "Broahoho",
    "Buoso",
    "Buoyem",
    "Busuama",
    "Busunya",
    "Cherembo",
    "Chiranda",
    "Chirehin",
    "Chiripo",
    "Chirinbindasi",
    "Chopbaase",
    "Dafo",
    "Dawadawa Nos.1 & 2",
    "Deifour Battor",
    "Denteso",
    "Dogokrom",
    "Domiabra",
    "Donkro Nkwanta",
    "Dononso",
    "Dotobaa",
    "Dromankese",
    "Dromankuma",
    "Duabone",
    "Dumso",
    "Dwankrom",
    "Dwija",
    "Efuma",
    "Faaman",
    "Fakwasi",
    "Fiaso",
    "Fiema",
    "Forikrom",
    "Fulanikrom",
    "Garadima",
    "Gbongbonyah",
    "Gulumpe",
    "Hwidiem",
    "Jato",
    "Jema",
    "Kadelso",
    "Kadue",
    "Kajai",
    "Kajaji",
    "Kaka",
    "Kamampa",
    "Kandige",
    "Kapro",
    "Kasanga",
    "Kintampo",
    "Kofi Djan",
    "Kofikuma",
    "Kofoso",
    "Kojo Boffour",
    "Kojokrom",
    "Kokofu",
    "Kokuma",
    "Komfourkrom",
    "Kongoja",
    "Konkonse",
    "Konkrompe",
    "Kontonso",
    "Krabonso",
    "Kranka",
    "Krobo (Techiman N)",
    "Krobo (Pru)",
    "Krobo (Sene)",
    "Kumfia",
    "Kunsu",
    "Kuntunso",
    "Kwaehunu",
    "Kwame Danso",
    "Kyeredeso",
    "Labun",
    "Lafiaru",
    "Lamu",
    "Langasi",
    "Lassi",
    "Lobi",
    "Longoro",
    "Mansie",
    "Manso",
    "Mantukwa",
    "Mframa",
    "Miawani",
    "Mmaampehia",
    "Mpem",
    "Nante",
    "New Longoro",
    "Nipadikru",
    "Nkoranza",
    "Nkrankrom",
    "Nkonsia",
    "Nkwabeng",
    "Nsuta",
    "Ntankro",
    "Ntariban",
    "Ntereso",
    "Ntonaboma",
    "Ntobriso",
    "Nwowam",
    "Nyankontre",
    "Nyomoase",
    "Offuman",
    "Pamdu",
    "Paninamisa",
    "Pebiastre",
    "Pienyina",
    "Pinihin",
    "Portor",
    "Prang",
    "Premuase",
    "Pruso",
    "Pumpuano",
    "Pumpumtifi",
    "Sabogira",
    "Sabule",
    "Sogliboi",
    "Sanwakyi",
    "Sawboi",
    "Sebreni",
    "Seneso",
    "Senya",
    "Sikaa",
    "Siso",
    "Sora",
    "Soronuase",
    "Srapukrom",
    "Subingya",
    "Tadieso",
    "Tahima",
    "Tanfiano",
    "Tanfiano No.2",
    "Tanoboase",
    "Tanoso",
    "TECHIMAN",
    "Temebabi",
    "Timiabu",
    "Tentare",
    "Trohwe",
    "Tuobodom",
    "Twimia Nkwanta",
    "Waso",
    "Watro",
    "Weila",
    "Wiase",
    "Yabraso (A-A)",
    "Yabraso (Kintampo N)",
    "Yajau",
    "Yaokawkaw",
    "Yaw Pare",
    "Yefri",
    "Yeji",
    "Zabrama ",
  ]),
  (Central = [
    "Abaasa",
    "Abakrampa",
    "Abamkrom",
    "Abandze",
    "Abeadze Dominase",
    "Abiram",
    "Aboabo",
    "Aboase",
    "Abodom",
    "Abora",
    "Abrafo",
    "Abrafo Odumase",
    "Abrekum",
    "Abrem Agona",
    "Abreshia",
    "Abuakwa",
    "Abura Dunkwa",
    "Achiase (Denkyira)",
    "Achiase (Gomoa)",
    "Adaboi",
    "Adiembra",
    "Afiaso",
    "Afrangua",
    "Agona",
    "Agona Swedru",
    "Agyimpoma",
    "Ahotokurom",
    "Ajumako",
    "Akatakyiwa",
    "Akonfodi",
    "Akosua",
    "Arkra",
    "Akrampa",
    "Akropong (Assin)",
    "Akropong (Denkyira)",
    "Akwamu",
    "Akweley",
    "Amanfopong",
    "Amanful",
    "Amisakrom",
    "Amissano",
    "Amoaman",
    "Ampenkro",
    "Ampenyi",
    "Ananikrom",
    "Anhweansu",
    "Aniahu",
    "Ankaako",
    "Ankaase",
    "Ankaful",
    "Ankamu",
    "Ankwanda",
    "Anomabo",
    "Antado",
    "Anwiawia",
    "Anyinasu",
    "Apaa",
    "Apam",
    "Apewosika",
    "Asaafa",
    "Asafo",
    "Asamang",
    "Asasitre",
    "Asebu",
    "Asempanyin",
    "Asikuma",
    "Asokwa",
    "Assasan",
    "Assin Achiase",
    "Assin Adubiase",
    "Assin Akrofuom",
    "Assin Anyinabrim",
    "Assin Asempanaye",
    "Assin Besease",
    "Assin Bereku",
    "Assin Brofoyedur",
    "Assin Domeabra",
    "Assin Foso",
    "Assin Juaso",
    "Assin Kyinso",
    "Assin Manso",
    "Assin Nsuta",
    "Assin Nyankomasi",
    "Assin Odumasi",
    "Assin Praso",
    "Asuantsi",
    "Ataabadze",
    "Ateitu",
    "Attakwaa",
    "Awombrew",
    "Awisem",
    "Awutu Bereku",
    "Ayanfuri",
    "Ayeldu",
    "Ayensuako",
    "Ayaase",
    "Baifikrom",
    "Baako",
    "Bawjiase",
    "Bibianiha",
    "Bedum",
    "Benin",
    "Benyadze",
    "Bepoben",
    "Bepokokoo",
    "Berase",
    "Besease (Ajumako)",
    "Besease (Komenda)",
    "Bewadze",
    "Biriwa",
    "Bobikuma",
    "Brafoyaw",
    "Brakwa",
    "Breman Asikuma",
    "Bremang",
    "Brenu Akyinim",
    "Brimso",
    "Buabin",
    "Buabinso",
    "Buduburam",
    "Bukuruso",
    "CAPE COAST",
    "DabiNaMeWoHen",
    "Dabir",
    "Dago",
    "Dahom",
    "Darmang",
    "Dawurampong",
    "Denkyira Obuasi",
    "Diaso",
    "Dominase",
    "Dominase",
    "Dominase",
    "Dompim",
    "Dompoase",
    "Duakwa",
    "Dunkwa-on-Offin",
    "Dwenase",
    "Dwendwenbadze",
    "Efutu",
    "Eguafo",
    "Eguase",
    "Egyaa",
    "Ehwia",
    "Eyisam",
    "Ekon",
    "Ekrawfo",
    "Ekumpoano",
    "Ekurabadze",
    "Elmina",
    "Enyan Denkyira",
    "Enyanmaim",
    "Enyindakurom",
    "Essaman",
    "Essarkyir",
    "Esiam",
    "Essuekyir",
    "Fetteh",
    "Fianko",
    "Fosuansa",
    "Frami",
    "Gomoa Afransi",
    "Gomoa Ajumako",
    "Gomoa Assin",
    "Gomoa Brofo",
    "Gomoa Brofoyedur",
    "Gomoa Denkyira",
    "Gomoa Gyaman",
    "Gomoa Kumasi",
    "Gomoa Lome",
    "Gomoa Ngyeresi",
    "Gomoa Nkoranza",
    "Gomoa Odina",
    "Gomoa Oguaa",
    "Gomoa Tarkwa",
    "Gyahadze",
    "Gyangyanadze",
    "Gyinakuma",
    "Hasowodze",
    "Hemang",
    "Immuna",
    "Jacobkrom",
    "Jakai",
    "Jamra",
    "Jei Krodua",
    "Jira Akyinim",
    "Jukwa",
    "Jukwa Mfuom",
    "Kafodzidzi",
    "Kakanase",
    "Kakumdo",
    "Kasoa",
    "Katakyiase",
    "Kissi",
    "Kobina Ansah",
    "Kojo Beedu",
    "Kokoado",
    "Kokoben",
    "Kokoso",
    "Kokwado",
    "Komenda",
    "Kormantse",
    "Kotokyi",
    "Krobo",
    "Krofu",
    "Kruwa",
    "Kuntanase",
    "Kuntu",
    "Kurado",
    "Kushea",
    "Kwaata",
    "Kwaman",
    "Kwanyako",
    "Kweikrom",
    "Kwekukrom",
    "Kyekyewere",
    "Kyinaso",
    "Mampoma",
    "Mando",
    "Mankessim",
    "Mankoadze",
    "Mankrong",
    "Maudaso",
    "Mensakrom",
    "Meretweso",
    "Mesomagor",
    "Mfuom",
    "Moree",
    "Moseaso",
    "Mpeasem",
    "Mprumem",
    "Mumford",
    "Munianu",
    "Narkwa",
    "Nanabin",
    "Nfotoa",
    "Ninety",
    "Nkodwo",
    "Nkronua Anafo",
    "Nkum",
    "Nsaba",
    "Nsuaem-Kyekyewere",
    "Nsuekyir",
    "Ntafrewaso",
    "Ntom",
    "Nuamakrom",
    "Nwomaso",
    "Nyakrom",
    "Nyamedom",
    "Nyame ye Adom",
    "Nyanfueku Ekroful",
    "Nyankumasi Ahenkro",
    "Nyanyano",
    "Nyarkoadze",
    "Nyinase",
    "Nyinawusu",
    "Obidan",
    "Obokor",
    "Oboyambo",
    "Obrachire",
    "Obutu",
    "Ochiso",
    "Odoben",
    "Odumase",
    "Oduponkpehe",
    "Oguaa",
    "Oguakuma",
    "Ogyanhyewano",
    "Ojobi",
    "Okurukrom",
    "Ongwa",
    "Onyadze",
    "Otuam",
    "Pedu",
    "Penim",
    "Pinanko",
    "Potsin",
    "Queen Anne's Point",
    "Saltpond",
    "Sankor",
    "Senya Bereku",
    "Seth Okai",
    "Sibinso",
    "Sobroso",
    "Srafa",
    "Sunkwaa",
    "Suprudo",
    "Techiman",
    "Towboase",
    "Topiase",
    "Tumfokor",
    "Twifo Mampong",
    "Twifo Praso",
    "Wawase",
    "Weremaso",
    "Winneba",
    "Woarabeba",
    "Wompam",
    "Wurakese",
    "Wuwuso",
    "Yamoransa",
  ]),
  (Eastern = [
    "Abaam",
    "Abakoase",
    "Abenase",
    "Abene",
    "Abetifi",
    "Abetim",
    "Abirem",
    "Abiriw",
    "Aboabo Halt",
    "Abodom",
    "Abomasarefo",
    "Abomosu",
    "Abompe",
    "Abonse",
    "Abotakyi",
    "Aburi",
    "Achiase",
    "Adamorobe",
    "Adankrono",
    "Adasawase",
    "Adausena",
    "Adawso",
    "Addo Nkwanta",
    "Addonkwanta",
    "Adeiso",
    "Adenkrebi",
    "Adjeikrom",
    "Adjena",
    "Adjobue",
    "Adoagyiri",
    "Aduamoa",
    "Aduasa",
    "Adubiase",
    "Adukofi",
    "Adukrom",
    "Adumasa",
    "Adwafo",
    "Afosu",
    "Aframso (Krobo)",
    "Aframso (Kwahu)",
    "Aglobo",
    "Agomanya",
    "Agordeke",
    "Agotime",
    "Agu",
    "Agyata",
    "Ahamahama",
    "Ahinase",
    "Ahwerease",
    "Akagla",
    "Akanteng",
    "Akatawia",
    "Akenkansu",
    "Akim Asene",
    "Akim Asuboa",
    "Akim Hemang",
    "Akim Oda",
    "Akim Swedru",
    "Akokoaso",
    "Akorabo",
    "Akoraso",
    "Akosombo",
    "Akotuakrom",
    "Akropong",
    "Akropong (Akim)",
    "Akroso",
    "Akrusu",
    "Akuase",
    "Akuse",
    "Akwadum",
    "Akwamufie",
    "Akwasiho",
    "Akwatia",
    "Amanase",
    "Amanfro",
    "Amanfrom Station",
    "Amankwa Tornu",
    "Amankwakrom",
    "Amanokrom",
    "Amedeka",
    "Ampedwae",
    "Ampofokurom",
    "Amoa",
    "Amuana Praso",
    "Anamase",
    "Ankaase",
    "Ankomah",
    "Anlo Faaso",
    "Anum",
    "Asikuma",
    "Anyaboni",
    "Anyinam",
    "Anyinase",
    "Anyinasin",
    "Apapam",
    "Apedwa",
    "Aperade",
    "Apimsu",
    "Apinamang",
    "Apirede",
    "Apoli",
    "Apradan",
    "Aprokumase",
    "Asafo",
    "Asakraka",
    "Asamama",
    "Asamankese",
    "Asantemang",
    "Aseseeso",
    "Asesewa",
    "Asiakwa",
    "Asikasu",
    "Asikasu Odumase",
    "Asokore",
    "Asuboi",
    "Asuboni",
    "Asuboni Rails",
    "Asunafo",
    "Asuokaw",
    "Asuom",
    "Asuoso",
    "Asuoyaa",
    "Atiankama",
    "Atibie",
    "Atikpale",
    "Atimpoku",
    "Atweasin",
    "Avatime",
    "Awaham",
    "Awenare",
    "Awisa",
    "Awukugua",
    "Awunakrom",
    "Ayirebi",
    "Badukrom",
    "Banso",
    "Begoro",
    "Bepoase",
    "Bepong",
    "Berekuso",
    "Bewase",
    "Bisa",
    "Boadua",
    "Boakyekrom",
    "Bokuruwa",
    "Bormase",
    "Bomso",
    "Bonkron",
    "Boso",
    "Bosuso",
    "Bowkrom",
    "Brenase",
    "Brepaw",
    "Bridgease",
    "Bukunor",
    "Bukuso",
    "Bunso",
    "Buyiri",
    "Chebi Aboho",
    "Chia",
    "Coaltar",
    "Danso",
    "Dawa Jakoru",
    "Dawu",
    "Dedeso",
    "Dedeso Wireko Nos.1&2",
    "Densuso",
    "Dobro",
    "Dodi",
    "Domi",
    "Dominase",
    "Donkorkrom",
    "Edimso",
    "Effiduase",
    "Enyiresi",
    "Eshiem",
    "Faaso",
    "Fankyeneko",
    "Faso",
    "Forifori",
    "Fradaka",
    "Frankadua",
    "Gyadam",
    "Gyakiti",
    "Gyankama",
    "Huhunya",
    "Hweakwae",
    "Hweehwee",
    "Jebikura",
    "Jejeti Nkwanta",
    "Jumapo",
    "Kade",
    "Kadewaso",
    "Kankan",
    "Kaple",
    "Kibi",
    "Klo Akwapim",
    "Kodidi",
    "Kodobeda",
    "Kofi Kyere",
    "Kofi Pare",
    "KOFORIDUA",
    "Kokobeng",
    "Kokotintin",
    "Kokronpe",
    "Konko",
    "Konkonuru",
    "Kotiyeabua",
    "Kotokuom",
    "Kotoso",
    "Kpong",
    "Kraboa",
    "Krobo Odumase",
    "Kukurantumi",
    "Kumikrom",
    "Kusi",
    "Kwao-Baa",
    "Kwabeng",
    "Kwae",
    "Kwaekese",
    "Kwahu Jejeti",
    "Kwahu Praso Nos.1&2",
    "Kwahu Tafo",
    "Kwawu Adowso",
    "Kwamoso",
    "Kwanta",
    "Kwasi Addae",
    "Kyenkularbi",
    "Lakpa",
    "Larteh",
    "Maame Dede",
    "Maase",
    "Madam",
    "Marfokrom",
    "Mamanso",
    "Mamfe",
    "Mampong",
    "Mampong Nkwanta",
    "Mangoase",
    "Manso",
    "Manyakpongunor",
    "Mem Chemfre",
    "Mepom",
    "Mmetiamu",
    "Mofram",
    "Monsie",
    "Mopti",
    "Mpaem",
    "Mpraeso",
    "Nankese",
    "New Abirem",
    "New Adjena",
    "New Oworobong",
    "New Somanya",
    "New Tafo",
    "Nkami",
    "Nkawkaw",
    "Nkronso",
    "Nkurakan",
    "Nkwantanan",
    "Nkwantanang",
    "Nkwarteng",
    "Nkwatia",
    "Nkyenenkyene",
    "Nnudu",
    "Nsawam",
    "Nsempoamiensa Halt",
    "Nsutam",
    "Nteso",
    "Ntoaso",
    "Ntronang",
    "Nuaso",
    "Nwinso",
    "Nyafomang",
    "Nyame Nti",
    "Nyamebekyere",
    "Nyanawase",
    "Nyankomase",
    "Obo",
    "Obooho",
    "Obenyemi",
    "Obodan",
    "Obomeng",
    "Obosomase",
    "Obuotumpan",
    "Oda Nkwanta",
    "Odumasua",
    "Ofoase",
    "Ofoasekuma",
    "Oframase",
    "Okra Adjei Nos.1&2",
    "Okrakwadwo",
    "Okorase",
    "Okurase",
    "Okwenya",
    "Old Tafo",
    "Onuku",
    "Onyemso",
    "Onyimso",
    "Oparekrom",
    "Opersika",
    "Osenase",
    "Osiem",
    "Osino",
    "Osorase",
    "Oterkpolu",
    "Otrokper",
    "Otumi",
    "Otwereso",
    "Oyoko",
    "Pabi",
    "Pakro",
    "Panpanso",
    "Pankese",
    "Pano",
    "Peduase",
    "Pepease",
    "Potroase",
    "Pramkese",
    "Pramkuma",
    "Prasokuma",
    "Saafe",
    "Sakyikrom",
    "Samanhyia",
    "Sapor",
    "Sekesua",
    "Senchi",
    "Sesiamang",
    "Sikabeng",
    "Somanya",
    "Somsei",
    "Suhum",
    "Suhyen",
    "Suponso",
    "Tadieso",
    "Takorase",
    "Takrowase",
    "Takwa",
    "Takyiman",
    "Tenurase",
    "Teacher Mante",
    "Tease",
    "Tinkong",
    "Tortibo",
    "Trom",
    "Tumfa",
    "Tutu",
    "Twenedurase",
    "Whanabenya",
    "Wirenkyeren Amanfrom",
    "Wenchi",
    "Worobong",
    "Xedzodzoekope",
    "Yakoko",
    "Yensiso",
  ]),
  (Greater_Accra = [
    "Abeka",
    "Abelenkpe",
    "Abetinso",
    "Ablekuma",
    "Abokobi",
    "Abominya",
    "ACCRA",
    "Accra New Town",
    "Achimota",
    "Ada Foah",
    "Ada Panya",
    "Adentan",
    "Adjen Kotoku",
    "Adjiringanor",
    "Afienya",
    "Agbenyegakope",
    "Agomeda",
    "Ahanya",
    "Ahwiam",
    "Akplabanya",
    "Akweteman",
    "Alajo",
    "Alavanyo",
    "Alorkpem",
    "Amasaman",
    "Amlakpo",
    "Amrahia",
    "Anumle",
    "Anyakpor",
    "Apenkwa",
    "Asaprochona",
    "Ashaiman",
    "Ashalaja",
    "Ashaley Botwe",
    "Ashieye",
    "Ashongman",
    "Asutsuare",
    "Ayetepa",
    "Ayikuma",
    "Azizanya",
    "Baatsonaa",
    "Bawaleshie",
    "Big Ada",
    "Boi",
    "Bortianor",
    "Buaku",
    "Bubiashie",
    "Burma Camp",
    "Christiansborg",
    "Chuim",
    "Danchira",
    "Dansoman",
    "Darkuman",
    "Dawa",
    "Dawhenya",
    "Dodowa",
    "Dome",
    "Doryumu",
    "Dzorwulu",
    "Faajiemohe",
    "Fantevikope",
    "Fiakonya",
    "Gbawe",
    "Gigedokum",
    "Goi",
    "Gonse",
    "Haatso",
    "Huapa",
    "Jamestown",
    "Kaja",
    "Kasunya",
    "Katamanso",
    "Kodiabe",
    "Kokomlemle",
    "Kokrobitey",
    "Koluedor",
    "Kopodor",
    "Kotobabi",
    "Kpatsedor",
    "Kpetsupanya",
    "Kpehe",
    "Kpone",
    "Kpotsum",
    "Kpongunor",
    "Kposi",
    "Kubekro",
    "Kunyenya",
    "Kutunse",
    "Kwabenya",
    "Kwashieman",
    "La",
    "Langma",
    "Lartebiokorshie",
    "Legon",
    "Lekpongunor",
    "Lolonya",
    "Lorlorvor",
    "Lupunya",
    "Maajor",
    "Madina",
    "Magbomada",
    "Mamobi",
    "Mampehia",
    "Mamprobi",
    "Mangotsonya",
    "Manya Jorpanya",
    "Matsekope",
    "Manhean",
    "Mantseman",
    "Mataheko",
    "Mayera",
    "Medie",
    "Minya",
    "Miotso",
    "Mlitsakpo",
    "Mpehuasem",
    "New Ningo",
    "Ngleshie Amanfro",
    "Nima",
    "Nkwantanang",
    "Nsakina",
    "Nsuobri",
    "Nungua",
    "Nyapienya",
    "Nyigbenya",
    "Obakrowa",
    "Obeyeyie",
    "Oblogo",
    "Odaw",
    "Odumse",
    "Ocanseykope",
    "Ofankor",
    "Okorhuem",
    "Old Ningo",
    "Onyansana",
    "Oshiyie",
    "Osu",
    "Osudoku",
    "Osuwem",
    "Otinibi",
    "Oyarifa",
    "Oyibi",
    "Pantang",
    "Papao",
    "Papase",
    "Pena",
    "Pokuase",
    "Prampram",
    "Pute",
    "Sakumono",
    "Samsam",
    "Santeo",
    "Sege",
    "Sege Donya",
    "Sesemi",
    "Shai Hills Station",
    "Shiashie",
    "Some",
    "Songonya",
    "Sota",
    "Sowotuom",
    "Suapa",
    "Sugbanyate",
    "Tekpekope",
    "Tema",
    "Tema Community 18",
    "Tekpanya",
    "Tesa",
    "Tesano",
    "Teshie",
    "Toflokpo",
    "Togbloku",
    "Totimekope",
    "Totope",
    "Tsokomey",
    "Vakpo",
    "Weija",
    "Wiaboman",
    "Wokumagbe",
    "Wuonyi",
    "Zanidaw",
  ]),
  (North_East = [
    "Adaaribia",
    "Adari",
    "Akunuyi",
    "Awarike",
    "Baaduuri",
    "Bangbale",
    "Barelung",
    "Bima",
    "Bimbago",
    "Binde",
    "Biyemba",
    "Bjambigi",
    "Boaterigu",
    "Boiyeni",
    "Boku",
    "Bongpulugu",
    "Buakudow",
    "Bukasu",
    "Bulibia",
    "Bulkwere",
    "Bunbong",
    "Bunkpurugu",
    "Burugu",
    "Chereponi",
    "Chia",
    "Chirifoyiri",
    "Daazio",
    "Dagbiriboari",
    "Diani",
    "Dibisi",
    "Dintigi",
    "Djaguhuga",
    "Dobunyato",
    "Duu",
    "Famisa",
    "Fio",
    "Fungu",
    "Gambaga",
    "Ganzeeri",
    "Garinkuka",
    "Gbalo",
    "Gbandaa",
    "Gbangu",
    "Gbankoni",
    "Gbeo",
    "Gbimsi",
    "Gbintiri",
    "Gordi",
    "Guabuliga",
    "Jadema",
    "Jakpa",
    "Janga",
    "Jawani",
    "Jengendere",
    "Jilima",
    "Jimbale",
    "Jimbale",
    "Jimbale",
    "Junjungo",
    "Kablani",
    "Kambago",
    "Karimenga",
    "Katigri",
    "Kinkandina",
    "Kolik",
    "Kolinvai",
    "Konkoro",
    "Kpani",
    "Kparigu",
    "Kpasenkpe",
    "Kpatani",
    "Kpatiritinga",
    "Kpatorigu",
    "Kpatuse",
    "Kpukpabobgu",
    "Kpukparigbinni",
    "Kubori",
    "Kubugu",
    "Kudani",
    "Kukkagbinni",
    "Kukua",
    "Kulunga",
    "Kumun",
    "Kunchalum",
    "Kunkwa",
    "Kusobi",
    "Laatari",
    "Lamirem",
    "Langbina",
    "Langbinsi",
    "Lare",
    "Loagri No.2",
    "Manie",
    "Masa Wase",
    "Mishio",
    "Mompotunbego",
    "Mozio",
    "Munweneohedi",
    "Nabale",
    "Nabansong",
    "Nabari",
    "Nabulic",
    "Nabukpeni",
    "Naduni",
    "Nagai",
    "Nagboo",
    "Najiri",
    "Nakaku",
    "Nakpanduri",
    "Nakpanzong",
    "Nakpenyeraga",
    "Nakurugu",
    "NALERIGU",
    "Namaasim",
    "Namiyili",
    "Namoo",
    "Nanbali",
    "Nandua",
    "Nangruma",
    "Nanguna",
    "Nanori",
    "Nanyeeri",
    "Nasia",
    "Nasuan",
    "Nayeri",
    "Nayirifong",
    "Noyaloabi",
    "Nyambanda",
    "Nyamijawga",
    "Nyamijawga",
    "Obaalaanu",
    "Pekura",
    "Perima",
    "Pwalagu",
    "Sagadugu",
    "Sakogu",
    "Sakori",
    "Sakpaba",
    "Salugu",
    "Salugu",
    "Samni",
    "Selinvoya",
    "Senta",
    "Soo",
    "Soansobgi",
    "Sooba",
    "Soyegu",
    "Sumniboma No.1",
    "Sumniboma No.2",
    "Sunkpungu",
    "Tacheku",
    "Tambing",
    "Tamboku",
    "Tambong",
    "Tando",
    "Tangbini",
    "Tantala",
    "Temaa",
    "Tempango",
    "Teten",
    "Tiya",
    "Tianoba",
    "Tichirigitaba",
    "Tiekasu",
    "Tigenga",
    "Tinchangu",
    "Tinguri",
    "Tinsungu",
    "Tintariga",
    "Tombu",
    "Tunni",
    "Tutu",
    "Tuzeaa",
    "Waku",
    "Walewale",
    "Wangao",
    "Wenchiki",
    "Wonjuga",
    "Wulugu",
    "Wungu",
    "Wuntubiri",
    "Wuyima",
    "Yagaba",
    "Yakpaga Mbureka",
    "Yama",
    "Yaroyili",
    "Yawgu",
    "Yezebisi",
    "Yikpabongu",
    "Yiteli",
    "Yizesi",
    "Yunyoo",
    "Zandua",
    "Zangbiyiri",
    "Zanghana",
    "Zangum",
    "Zangu-Yakura",
    "Zanwara",
    "Zikaya",
    "Ziniya",
    "Zua",
    "Zogiligu",
    "Zoorizugu",
  ]),
  (Northern = [
    "Achinayili",
    "Adayili",
    "Adayiri",
    "Adibo",
    "Aduyeli",
    "Afayili",
    "Alfayinga",
    "Anturo",
    "Azunkuli",
    "Baduli (Mion)",
    "Baduli (Nanumba)",
    "Bagale",
    "Bagurugu",
    "Bakpaba",
    "Bakuli",
    "Bakundiba",
    "Balai",
    "Bali",
    "Balo",
    "Bambuli",
    "Bandiyili",
    "Bangmani",
    "Bankamba",
    "Barbia",
    "Batani",
    "Bato",
    "Bawgo",
    "Bejim",
    "Benja",
    "Bilisinga",
    "Bimbilla",
    "Bincheratanga",
    "Binduli",
    "Bisayem",
    "Bladjai",
    "Blahogo",
    "Blinkpale",
    "Bodere",
    "Bolni",
    "Boma",
    "Bonboli",
    "Bong",
    "Bosenaire",
    "Bosoni",
    "Botaw",
    "Buguya",
    "Buguyili",
    "Bulawn",
    "Bulpiela",
    "Bunya",
    "Burai",
    "Burumani",
    "Butoe",
    "Chagbani",
    "Chakori",
    "Chamba",
    "Changnayili",
    "Cheogu",
    "Chichari",
    "Choggu Yapalsi",
    "D.C.Kura",
    "Dakpema",
    "Dakrubongo",
    "Damdabole",
    "Damdu",
    "Danayili",
    "Danyo",
    "Degbawa",
    "Demon",
    "Demonaayili",
    "Denie",
    "Diari",
    "Didjo",
    "Difa",
    "Dime",
    "Dinga",
    "Dinyogo",
    "Disiga",
    "Diziri",
    "Djagbemba",
    "Djaleba",
    "Djo",
    "Dobone",
    "Dogbam",
    "Dohini",
    "Dondonne",
    "Duko",
    "Dungu",
    "Duni",
    "Duuni",
    "Ekumdipe A",
    "Foshogo",
    "Fule",
    "Funga",
    "Gaa",
    "Garin Dade",
    "Garin Dogo",
    "Gariwe",
    "Gbambu",
    "Gbande",
    "Gbando",
    "Gbeni",
    "Gbogo",
    "Gbong",
    "Gbongbon",
    "Gbungbalaga",
    "Gieji",
    "Gjoe",
    "Gnani",
    "Gulubi",
    "Gumon",
    "Gunaayili",
    "Gundo",
    "Gunguni",
    "Gunsi",
    "Guntingli",
    "Gupanalgo",
    "Gushegu",
    "Gushie",
    "Jaburu",
    "Jagaba",
    "Jagere",
    "Jaguriyili",
    "Jakpa",
    "Jakpale",
    "Jakugu",
    "Jamalega",
    "Jamo",
    "Jankonyili",
    "Janyuni",
    "Jegrido",
    "Jegwa",
    "Jemaka",
    "Jerigo",
    "Jimam",
    "Jimle",
    "Jogoli",
    "Juali",
    "Juanayili",
    "Juo",
    "Ka",
    "Kabesi",
    "Kable",
    "Kabonwule",
    "Kachanki",
    "Kaiyong",
    "Kakpanjag",
    "Kambow",
    "Kanshegaw",
    "Kanvile",
    "Kapogu",
    "Karaga",
    "Kasampwi",
    "Katiajeli",
    "Kawkrugu",
    "Kedia",
    "Kengua",
    "Keshago",
    "Kitare",
    "Klugbani",
    "Kobiele",
    "Kojoboni",
    "Kolobo",
    "Komoayili",
    "Kosuri",
    "Kountja",
    "Kpabi",
    "Kpabia",
    "Kpadjaba",
    "Kpalba",
    "Kpaligaboni",
    "Kpalisogu",
    "Kpalon",
    "Kpalpulga",
    "Kpalsako",
    "Kpalsogu",
    "Kpanagjehae",
    "Kpanashie",
    "Kpandai",
    "Kpanjamba",
    "Kpankpan",
    "Kpatia",
    "Kpatinga",
    "Kpembik",
    "Kpinjingo",
    "Kpunduli",
    "Krukruba",
    "Kubalem",
    "Kubiko",
    "Kuduli",
    "Kugwigu",
    "Kuko",
    "Kukobila",
    "Kukpaligu",
    "Kukuo (Nanumba)",
    "Kukuo (Tamale)",
    "Kukuo",
    "Kukuo",
    "Kuli",
    "Kulkpanga",
    "Kulkpene",
    "Kumbungu",
    "Kupelugu",
    "Kusebi",
    "Kusibaw",
    "Kutung",
    "Kuyine",
    "Kwani",
    "Kyanshiogo",
    "Lahi",
    "Lamakara",
    "Lanja",
    "Lanto",
    "Legale",
    "Lepusi",
    "Loni",
    "Luluga",
    "Lungbunga",
    "Lungni",
    "Madjefo",
    "Makayili",
    "Malgone",
    "Marijaire",
    "Marone",
    "Mbanayili",
    "Mbatinga",
    "Mbosumbo",
    "Melshegaw",
    "Mojina",
    "Momo",
    "Moyer",
    "Munyiba",
    "Naboal",
    "Nabogu",
    "Nabon",
    "Nabuli",
    "Nabulugu",
    "Nachamba No.2",
    "Nadogo",
    "Nagale",
    "Nagbiegu",
    "Nahuyili",
    "Nakpa",
    "Nakpa",
    "Nakpabone",
    "Nakpali",
    "Nakpasala",
    "Nakpayili",
    "Nakundugu",
    "Nalolli",
    "Nalugu",
    "Nambiri",
    "Namburugu",
    "Namongbani",
    "Namongbani",
    "Nananouri",
    "Nanong Nayiri",
    "Nanton",
    "Nanton Kurugu",
    "Nasamwiaga",
    "Nasia",
    "Nasiuk",
    "Nasumbongo",
    "Natago",
    "Navili",
    "Nawchugu",
    "Nawiago",
    "Nayiri",
    "Nayugu",
    "Niakwa",
    "Nion",
    "Niyibo",
    "Nkanchina",
    "Numbala",
    "Nurgu",
    "Nyaboku",
    "Nyambande",
    "Nyamkpala",
    "Nyankpala",
    "Nyansung",
    "Nyesie",
    "Ongoni",
    "Oti River",
    "Pabila",
    "Padjae",
    "Palari",
    "Palguni",
    "Pekuo",
    "Peo",
    "Pigu",
    "Pilteng",
    "Pion",
    "Pisigu",
    "Pong Tamale",
    "Potele",
    "Pulo",
    "Punja",
    "Pusuga",
    "Sabari",
    "Saboba",
    "Sabon Gida",
    "Sabonjida",
    "Safam",
    "Sagnarigu",
    "Sakku",
    "Sakpeolangbene",
    "Sakuba",
    "Sakulo",
    "Salamkpong",
    "Salnayili",
    "Salwelsi",
    "Samago",
    "Samboul",
    "Sambu",
    "Sampiamon",
    "Sanale",
    "Sanduli",
    "Sang",
    "Sangba",
    "Sangmamba",
    "Sanguli",
    "Sanguli (Saboba)",
    "Sanji",
    "Sato",
    "Savelugu",
    "Sekpe",
    "Sekpiegu",
    "Senjele",
    "Sheini",
    "Shindili",
    "Shiung",
    "Shogo",
    "Singa",
    "Soburi",
    "Sogo",
    "Sokoli",
    "Sunson",
    "Suruku",
    "Takoraya",
    "Tale",
    "Tale",
    "Talole",
    "Tamalago",
    "TAMALE",
    "Tampion",
    "Tanga",
    "Tanginga",
    "Tankpa",
    "Tapia",
    "Tarnamo",
    "Tasundo No.1",
    "Tatale",
    "Tatindo",
    "Tejenga",
    "Tibogona",
    "Tichecha",
    "Tijaw",
    "Tindan",
    "Tindang",
    "Tindongo (south)",
    "Tindongo (north)",
    "Tingelento",
    "Tobale",
    "Tobale",
    "Tolon",
    "Tonayili",
    "Tononoli",
    "Tori",
    "Tugu",
    "Tuosango",
    "Tuwua",
    "Tuya",
    "Umpigo",
    "Vani",
    "Vitin",
    "Vogo",
    "Wabuli",
    "Wadigo",
    "Waduru",
    "Walbogo",
    "Wanpale",
    "Wapuli",
    "Warabu",
    "Warlung",
    "Wasendaw",
    "Wassando",
    "Wawu",
    "Weni",
    "Wulensi",
    "Wuli",
    "Yabologu",
    "Yakpaba",
    "Yaoyili",
    "Yapala",
    "Yapalsi",
    "Yawgo",
    "Yemo Karaga",
    "Yendi",
    "Yilonayili",
    "Yipieliga",
    "Yiyamba",
    "Yong",
    "Zabzugu",
    "Zagbeli",
    "Zandua",
    "Zangbalung",
    "Zantana",
    "Zawire",
    "Ziluno",
    "Zinindo",
    "Ziong",
    "Ziro",
    "Zogaw",
    "Zokuga",
    "Zoya",
    "Zulawgwaw",
    "Zuo",
    "Zuorugu",
  ]),
  (Oti = [
    "Abetenase",
    "Aboabo",
    "Abohire",
    "Abrewankor",
    "Abrubruwa",
    "Adjana",
    "Adonkwanta",
    "Adumadum",
    "Ahamansu",
    "Ahinkro",
    "Ahondwo",
    "Akaa",
    "Akaniem",
    "Akayao",
    "Akposo Kabo",
    "Akroso",
    "Ampeyo",
    "Ankaase",
    "Apaso",
    "Apesokubi",
    "Asato",
    "Ashiabre",
    "Asuboe",
    "Asukawkaw",
    "Atafie",
    "Atakofi",
    "Atonkor",
    "Attakrom",
    "Ayirafie",
    "Bejamse",
    "Baglo",
    "Baika",
    "Banda",
    "Banka",
    "Bodada",
    "Bonakye",
    "Bontibor",
    "Bora",
    "Borae No.2",
    "Bowiri Amanfrom",
    "Bowiri Anyinase",
    "Bowiri Kyirahin",
    "Bowiri Odumase",
    "Brewaniase",
    "Boafri",
    "Bumbula",
    "Chaiso",
    "Chantai",
    "Chillinga",
    "Chinderi",
    "Dadiase",
    "DAMBAI",
    "Dapaa",
    "Dapaa Junction",
    "Dentemanso",
    "Dentu",
    "Dodi Aboabo",
    "Dodi Mempeasem",
    "Dodi Papase",
    "Dodo Amanfrom",
    "Dodo Pepesu",
    "Dodo Tamale",
    "Dodofie",
    "Domiabra",
    "Dormabin",
    "Dufrumkpa",
    "Dzindziso",
    "Dzolu",
    "Ehiamankyene",
    "Fankyeneko",
    "Gekrong",
    "Grubi",
    "Guaman",
    "Jasikan",
    "Kadengben",
    "Kadjebi",
    "Kakraka",
    "Kankyenkura",
    "Kantankufri",
    "Katanga",
    "Kechebi",
    "Keri",
    "Kete Krachi",
    "Kodibenum",
    "Korantai",
    "Koto Nkwanta",
    "Kue",
    "Kpassa",
    "Kpatchu",
    "Kradente",
    "Kromase",
    "Kudje",
    "Kunda",
    "Kute",
    "Kwadjobri",
    "Kwamekrom",
    "Lonto",
    "Mamata",
    "Menuso",
    "Monkra",
    "Motoka",
    "Mpusato",
    "New Ayoma",
    "New Otiso",
    "Ngbanye",
    "Nkatekwan",
    "Nkonya Ahenkro",
    "Nkonya Ntumda",
    "Nkonya Tepo",
    "Nkonya Wurupong",
    "Nkwanta",
    "Nkyenenkyene",
    "Nsuogya",
    "Nsuta",
    "Ntewusae",
    "Nyakoma",
    "Nyambong",
    "Obanda",
    "Odomi",
    "Odumase Adele",
    "Okadjakrom",
    "Okomfukrom",
    "Okorakojo",
    "Okorede",
    "Old Ayoma",
    "Osramanae",
    "Otiso",
    "Pampawie",
    "Papatia",
    "Pawa",
    "Poase Cement",
    "Pusupu",
    "Salifukrom",
    "Shiare",
    "Takrabe",
    "Tapa Abotoase",
    "Tapa Amanfrom",
    "Tapa Amanya",
    "Tapa Brewaniase",
    "Tapa Odei",
    "Tariaso",
    "Teteman",
    "Tokroso",
    "Tokuroanu",
    "Tuntino",
    "Tutukpene",
    "Twereso",
    "Wankayo",
    "Wawaso",
    "Worawora",
    "Zongo Macheri",
  ]),
  (Savannah = [
    "Abrumase",
    "Achubunyo",
    "Agbegikrom",
    "Agbelikame No.1",
    "Anyanto",
    "Babator",
    "Bagapi",
    "Bagbiapi",
    "Baka",
    "Bale",
    "Bambalayuro",
    "Bamboi",
    "Bambuli",
    "Banvim",
    "Banda Nkwanta",
    "Bandown",
    "Baso",
    "Bau",
    "Bawena",
    "Bentripe",
    "Biama",
    "Bidima",
    "Bilige",
    "Boakyipe",
    "Bole",
    "Bomburi",
    "Bonipe",
    "Bonyanto",
    "Bortupure",
    "Bugay",
    "Bugsa",
    "Buipe",
    "Buma",
    "Bung",
    "Bungweli",
    "Bunjai",
    "Busunu",
    "Butei",
    "Butugu",
    "Carpenter",
    "Chache",
    "Chama",
    "Chambuligu",
    "Chandayili",
    "Changbuni",
    "Chibrinyoa",
    "Chokosipe",
    "Chungasi",
    "Chutadi",
    "Dabope",
    "Daboya",
    "Daboyeri",
    "Dabuori",
    "Dagbibu",
    "Dagonkade",
    "Dakrupe",
    "DAMONGO",
    "Danivaar",
    "Deba",
    "Deboko",
    "Delanyin",
    "Deniyiri",
    "Denkerepe",
    "Digma",
    "Dingoni",
    "Dochire",
    "Doli",
    "Donkonpe",
    "Fishilla",
    "Frago",
    "Fuchmbluma",
    "Fufulso",
    "Fumbo",
    "Fuu",
    "Gakuon",
    "Gbampe",
    "Gbampewa",
    "Gbangbom",
    "Gbasinkpa",
    "Gbenfu",
    "Gbenshe",
    "Gbogdaa",
    "Gbongbonduori",
    "Gida Wichie",
    "Gindabor",
    "Gitase",
    "Glinikula",
    "Goreba",
    "Gruma",
    "Grunshie Zongo",
    "Grunyu",
    "Grupe",
    "Gua",
    "Gyafo",
    "Horuyiri",
    "Jama",
    "Jang",
    "Janikura",
    "Jantilla",
    "Jantong",
    "Jantoo Kuko",
    "Jentilpe",
    "Jerayili",
    "Jeyiri",
    "Jilinkon",
    "Jimarian",
    "Jinfronu",
    "Jinkrom",
    "Jinlo",
    "Jogboi",
    "Jongase",
    "Jonokponto",
    "Jukuku",
    "Kabache",
    "Kabako",
    "Kabalima",
    "Kabampe",
    "Kabulembu",
    "Kachasi",
    "Kadeng",
    "Kafaba",
    "Kakiase",
    "Kakoshi",
    "Kalba",
    "Kanakulai",
    "Kananto",
    "Kandinga",
    "Kaukurugi",
    "Kayeresu",
    "Kbolebi",
    "Kiape",
    "Kidengi",
    "Kigbatito",
    "Kijew",
    "Kinyange",
    "Kitempe",
    "Kito",
    "Kluajon",
    "Kodregbuni",
    "Kojope",
    "Kolayili",
    "Kolofo",
    "Kolofo",
    "Kolonso",
    "Kong",
    "Konkori Camp",
    "Kopota",
    "Kotala",
    "Kpabuso",
    "Kpalang",
    "Kpalangase",
    "Kpalbe",
    "Kpalbusi",
    "Kpalguni",
    "Kpambu",
    "Kpandele",
    "Kpanshegu",
    "Kpasira",
    "Kpatinya",
    "Kpembe",
    "Kpongiri",
    "Krampo",
    "Kubeng",
    "Kukunde",
    "Kuli",
    "Kulmasa",
    "Kulpi",
    "Kumabuiye",
    "Kunfusi",
    "Kunkwa",
    "Kupua",
    "Kusawgu",
    "Kuto",
    "Kwame Kwasi",
    "Kwisini",
    "Lambo",
    "Lampol",
    "Lamporga",
    "Lampur",
    "Lamsa",
    "Langatire",
    "Larabanga",
    "Latinkpa",
    "Leliegberi",
    "Lingbinsi",
    "Lucene",
    "Maluwe",
    "Mamayili",
    "Mamkuma",
    "Mandari",
    "Manful",
    "Mankpang",
    "Mankarigu",
    "Mankuma",
    "Masaka",
    "Mempeasem",
    "Meriche",
    "Mines",
    "Mognori",
    "Momo",
    "Mpaha",
    "Murugu",
    "Nabengu",
    "Nabori",
    "Nagbruguni",
    "Nahari",
    "Nakpok",
    "Nakwabi",
    "Nalori",
    "Nasoyiri",
    "Nialala",
    "Nyantan",
    "Nyeshilla",
    "Ningboyili",
    "Nkamandei",
    "Ntereso",
    "Ntereso",
    "Nyamaliga",
    "Nyange",
    "Nyawuripe",
    "Nyoli",
    "Old Makango",
    "Palu",
    "Pataragu",
    "Pokrodanga",
    "Puil",
    "Sabongida",
    "Sagya",
    "Sakpa",
    "Sala",
    "Salaga",
    "Sangba",
    "Sangyeri",
    "Sankpala",
    "Saru",
    "Sawla",
    "Semisi",
    "Seripe",
    "Seyiri",
    "Signekura",
    "Sihiri",
    "Silimanchu",
    "Sisipe",
    "Soalepe",
    "Soma",
    "Sonyo",
    "Sopirtso",
    "Sumpini",
    "Taari",
    "Tailorpe",
    "Tainaboi",
    "Takpili",
    "Talkpa",
    "Tamankala",
    "Tangni",
    "Tankpe",
    "Tawinchela",
    "Teselima",
    "Tinga",
    "Tinkpanga",
    "Tolundipe",
    "Tulewe",
    "Tuna",
    "Turumi",
    "Vano",
    "Wakawaka",
    "Wambong",
    "Wangasi Turu",
    "Wasipe",
    "Yabum",
    "Yahayape",
    "Yala",
    "Yala",
    "Yapei",
    "Yezori",
    "Yipala",
    "Yipala",
    "Yipala",
    "Yirkpani",
    "Zankun",
    "Zantege",
    "Zawgu",
  ]),
  (Upper_East = [
    "Abelio",
    "Achanyeri",
    "Adaboya",
    "Adonsi",
    "Akpiokyeri",
    "Akundawi",
    "Amodalgo",
    "Apodabogo",
    "Arabe",
    "Asong",
    "Bachongsa",
    "Bador",
    "Balure",
    "Baribari",
    "Bawku",
    "Baziengo",
    "Bazua",
    "Bechisi",
    "Belagu",
    "Belungu",
    "Bilinsa",
    "Bimpella",
    "Bimpielega",
    "Binaba",
    "Binduri",
    "Bisigu",
    "Biu",
    "Biung",
    "Bonia",
    "BOLGATANGA",
    "Bongo",
    "Boya",
    "Bugri",
    "Bugula",
    "Bulpielise",
    "Bulunga",
    "Chansia",
    "Chiana",
    "Chuchuliga",
    "Dakrenia",
    "Danvonga",
    "Datoko",
    "Doba",
    "Dobogo",
    "Doninga",
    "Farfar",
    "Feo",
    "Fisa",
    "Fumbisi",
    "Gaani",
    "Gabuliga",
    "Gaga",
    "Gangoboka",
    "Gari",
    "Garu",
    "Gbedema",
    "Gbedembilisi",
    "Gia",
    "Gobasa",
    "Gogo",
    "Goruma",
    "Gowrie",
    "Gozeisi",
    "Gundari",
    "Kabengo",
    "Kadema",
    "Kado",
    "Kagbiri",
    "Kalesesi",
    "Kalijiisa",
    "Kambozugu",
    "Kamega",
    "Kamsori",
    "Kanaansa",
    "Kandiga",
    "Kanjarga",
    "Katiu",
    "Kawmaka",
    "Kayoro",
    "Kejetia",
    "Kiau",
    "Kobdem",
    "Kologo",
    "Kologu",
    "Kolpeligu",
    "Kolsabulga",
    "Kpalsako",
    "Kpalugu",
    "Kpataar",
    "Kpikpira",
    "Kudu",
    "Kugpela",
    "Kugri",
    "Kugsabla",
    "Kuguriziegu",
    "Kuka",
    "Kultamse",
    "Kulumasa",
    "Kulungungu",
    "Kulupielugu",
    "Kumbude",
    "Kungongo",
    "Kunkwa",
    "Kusanaba",
    "Lamboya",
    "Longsa (Sandema)",
    "Longsa (Wiaga)",
    "Manga",
    "Mayoro",
    "Mirigu",
    "Missiga",
    "Mognori",
    "Na",
    "Nafkoliga",
    "Naga",
    "Najigo",
    "Nakong",
    "Namogo",
    "Nanchieyir",
    "Nangalkinia",
    "Nangodi",
    "Nati",
    "Natinga",
    "Navrongo",
    "Nawognia",
    "Nayagnia",
    "Nogsenia",
    "Nung",
    "Nyanbisi",
    "Owosi",
    "Paga",
    "Paga Buru",
    "Pelungu",
    "Pinda",
    "Pulimakom",
    "Pungu",
    "Pusiga",
    "Pwalugu",
    "Saka",
    "Sakote",
    "Sambolugu",
    "Sambrungo",
    "Sandema",
    "Santeng",
    "Sapeliga",
    "Sherigu",
    "Shia",
    "Shiega",
    "Shiega",
    "Shishe",
    "Sinibaga",
    "Siniensi",
    "Sirigu",
    "Sonboko",
    "Songo",
    "Tambog",
    "Tandem",
    "Tanga (Navrongo)",
    "Tanga (Bawku)",
    "Taraganga",
    "Tempane",
    "Tengzuk",
    "Terago",
    "Teshie",
    "Tesung",
    "Tiedema",
    "Tilli",
    "Tindongo",
    "Tinsungu",
    "Tokwari",
    "Tongo",
    "Tubongu",
    "Tula",
    "Uwasi",
    "Vare",
    "Vea",
    "Voko",
    "Vundum",
    "Wiaga",
    "Widana",
    "Widnaba",
    "Wiesi",
    "Winduri",
    "Wingo",
    "Winkogo",
    "Woricombo",
    "Woriyanga",
    "Wupiensa",
    "Yandawa",
    "Yelania",
    "Yipaala",
    "Yipien",
    "Yorogo",
    "Zabugu",
    "Zabzundi",
    "Zandoya",
    "Zanwure",
    "Zawse",
    "Zebilla",
    "Zoko",
    "Zombaw",
    "Zongoiri",
    "Zuarungu",
    "Zuongo",
  ]),
  (Upper_West = [
    "Baayiri",
    "Baazu",
    "Babile",
    "Babujan",
    "Bagri",
    "Balafile",
    "Bamkpoma",
    "Bantala",
    "Banwon",
    "Base",
    "Basebelle",
    "Basiasan",
    "Bawkolo",
    "Bayeba Tiging",
    "Bellu",
    "Bende",
    "Benebise",
    "Benya",
    "Beriyem",
    "Bichemboi",
    "Bielepong",
    "Billaw",
    "Bisikan",
    "Bo",
    "Boe",
    "Bofiama",
    "Boli",
    "Boro",
    "Boti",
    "Brifo",
    "Bugu",
    "Bugubelle",
    "Bujan",
    "Bulenga",
    "Burufu",
    "Busa",
    "Busie",
    "Chago",
    "Chaksia",
    "Chala",
    "Challu",
    "Chang",
    "Chango",
    "Chapuri",
    "Charia",
    "Chasia",
    "Chawuli",
    "Chebagga",
    "Chelian",
    "Cherepon",
    "Chesa",
    "Dabo",
    "Daffiama",
    "Dagueri",
    "Dariguoyiri",
    "Dasima",
    "Dasuri",
    "Deriyiri",
    "Dimajan",
    "Dodiyiri",
    "Dogberri",
    "Doguba",
    "Dolibizon",
    "Donweni",
    "Dorimon",
    "Dorko",
    "Doung",
    "Dounjang",
    "Du",
    "Du",
    "Du",
    "Dubia",
    "Ducie",
    "Dupare",
    "Duri",
    "Duunonyuali",
    "Eremon",
    "Fatchu",
    "Fian",
    "Fielmuo",
    "Fina",
    "Funsi",
    "Furu",
    "Ga",
    "Gaapare",
    "Gbaliwob",
    "Gbari",
    "Gberi",
    "Gbo",
    "Gegempwe",
    "Gonggo",
    "Goriyiri",
    "Guri",
    "Guropisi",
    "Gurumbelle",
    "Gwal",
    "Gwasi",
    "Gwasi",
    "Gwo",
    "Gwo",
    "Gwollu",
    "Halembei",
    "Halemboi",
    "Hamile",
    "Hamoro",
    "Han",
    "Happa",
    "Hiel",
    "Igentu",
    "Issa",
    "Jang",
    "Jangoasi",
    "Janko",
    "Janvori",
    "Jawia",
    "Jeffisi",
    "Jefiyiri",
    "Jembogo",
    "Jerbuga",
    "Jeyiri",
    "Jijian",
    "Jirapa",
    "Jiripansi",
    "Jolinyiri",
    "Jumo",
    "Ka",
    "Kabaha",
    "Kadoli",
    "Kaha",
    "Kakalapari",
    "Kaleo",
    "Kalsara",
    "Kambaa",
    "Kampaha",
    "Kandia",
    "Kandiau",
    "Kangwo",
    "Kapachuhu",
    "Kari",
    "Karni",
    "Kassane",
    "Katekunu",
    "Katua",
    "Kawrawra",
    "Kayeni",
    "Kayinguasi",
    "Kinkele",
    "Kogri",
    "Kokoligu",
    "Kolpieni",
    "Koma",
    "Konchuri",
    "Kongolo",
    "Korinyiri",
    "Korro",
    "Kpala",
    "Kpata",
    "Kugia",
    "Kujopere",
    "Kulfuo",
    "Kulkarni",
    "Kulkpong",
    "Kulkwe",
    "Kulun",
    "Kunchugu",
    "Kundungu",
    "Kunfabela",
    "Kunsolo",
    "Kuntule",
    "Kunyebin",
    "Kunyukuo",
    "Kunzokala",
    "Kupulima",
    "Kuroboi",
    "Kusala",
    "Kwala",
    "Kwapun",
    "Lambussie",
    "Lawra",
    "Lilixia",
    "Liplime",
    "Lissa",
    "Loggo",
    "Mase",
    "Mawari",
    "Mengwe",
    "Methaw",
    "Mettoh",
    "Monojan",
    "Motigu",
    "Moyiri",
    "Nabolo",
    "Nabugang",
    "Nabugubelle",
    "Nadowli",
    "Nakora",
    "Nakpabia",
    "Namvili",
    "Nandom",
    "Nandomle",
    "Nanga",
    "Naro",
    "Nasa",
    "Nator",
    "Nawia",
    "Nebiewale",
    "New Navere",
    "Nimoro",
    "Nipilima",
    "Numbeg",
    "Nwanduonu",
    "Nyan",
    "Nyivil",
    "Nymitie",
    "Olbini",
    "Oli",
    "Olo",
    "Pagadana",
    "Pala",
    "Panyan",
    "Pari",
    "Pela",
    "Pepilime",
    "Pien",
    "Piiri",
    "Pina",
    "Ping",
    "Pirisi",
    "Pise",
    "Pisi",
    "Pofien",
    "Polli",
    "Pudo",
    "Pudonyoro",
    "Puleba",
    "Pulima",
    "Puzene",
    "Rus",
    "Saa",
    "Sabari",
    "Sabuli",
    "Sako",
    "Sakulo",
    "Salimana",
    "Samambaw",
    "Sambo",
    "Samoa",
    "Sangwia",
    "Sankana",
    "Santijan",
    "Sawobe",
    "Segri",
    "Sekai",
    "Sentia",
    "Serepere",
    "Sihiduori",
    "Sihoti",
    "Silbelle",
    "Sing",
    "Soaw",
    "Sobayiri",
    "Sogla",
    "Sombisi",
    "Somburo",
    "Sorbelle",
    "Sugu",
    "Taalipuo",
    "Tabeasi",
    "Tabiahe",
    "Talawona",
    "Taliasi",
    "Tampaala",
    "Tampala",
    "Tanchara",
    "Tangasi",
    "Tanina",
    "Taninaha",
    "Tanla",
    "Tantuo",
    "Tantuosi",
    "Tanvele",
    "Tapania",
    "Tappo",
    "Tasaw",
    "Tiboro",
    "Tiisa",
    "Timbia",
    "Tinniabe",
    "Tizza",
    "Tokali",
    "Tolibri",
    "Tomayiri",
    "Tome",
    "Torsa",
    "Toyanperi",
    "Tugu",
    "Tumu",
    "Tuopare",
    "Tuori",
    "Twadi",
    "Ulu",
    "Vamboi",
    "Vapor",
    "Vapor",
    "Varinpere",
    "Vere",
    "Vinving",
    "WA",
    "Wahabu",
    "Wallembelle",
    "Wapali",
    "Wechiau",
    "Wiiro",
    "Wogu",
    "Wotumu",
    "Wuru",
    "Yagha",
    "Yakanebi",
    "Yala",
    "Yaro",
    "Yibile",
    "Yikpee",
    "Yiziri",
    "Zambo",
    "Zambuluga",
    "Zang",
    "Zini",
  ]),
  (Volta = [
    "Abehenease",
    "Ablonu",
    "Abor",
    "Aborlove",
    "Abortia",
    "Abuadi",
    "Abutia Agorve",
    "Abutia Kloe",
    "Adafienu",
    "Adagbledu",
    "Adaklu Agblefe",
    "Adaklu Ahunda-Boso",
    "Adaklu Ahunda-Kpodzi",
    "Adaklu Goefe",
    "Adaklu Kpodzi",
    "Adexor",
    "Adexorkpodzi",
    "Adidokpoe",
    "Adidome",
    "Adina",
    "Adrume",
    "Adudornu",
    "Adutor",
    "Adzokoe",
    "Afango",
    "Afegame",
    "Afeyi",
    "Afife",
    "Aflao",
    "Agave",
    "Agavedzi",
    "Agbaflome",
    "Agbakope",
    "Agbedrafor",
    "Agbenorxoe",
    "Agblekpui",
    "Agblega",
    "Agbogbome",
    "Agbozume",
    "Agodeke",
    "Agordomi",
    "Agome",
    "Agorko",
    "Agornu Akporkplorte",
    "Agortime Beh",
    "Agortoe",
    "Agorvi",
    "Agotive",
    "Aveme Danyigba",
    "Ayiwata",
    "Akame",
    "Akatsi",
    "Aklakpanu",
    "Akoefe",
    "Akofafanami",
    "Akoviefe",
    "Akpafu Mempeasem",
    "Akpafu Odomi",
    "Akpafu Todzi",
    "Akpokope",
    "Akrofu Agorve",
    "Akrofu Xeviwofe",
    "Akuta",
    "Alakple",
    "Alavanyo Deme",
    "Alavanyo Dzogbedze",
    "Alavanyo Kpeme",
    "Alavanyo Wudidi",
    "Amedzikope",
    "Amedzofe",
    "Amutinu",
    "Anfoega",
    "Anfoeta Gbogame",
    "Anfoeta Tsebi",
    "Anfoega Tokome",
    "Anlo Afiadenyigba",
    "Anloga",
    "Anyako",
    "Anyanui",
    "Anyinawase",
    "Asadame",
    "Ashanti Kpoeta",
    "Atiavi",
    "Atikpui",
    "Atitekpo",
    "Atitekpoe",
    "Atiteti",
    "Atito",
    "Atorkor",
    "Atravenu",
    "Atsati",
    "Atsiati",
    "Atsiekpoe",
    "Avakpo",
    "Ave Afiadenyigba",
    "Ave Afiadenyigba Old Town",
    "Ave Kpedome",
    "Ave Xevi",
    "Avedzeme",
    "Avedzi",
    "Avenorpedo",
    "Avenorpeme",
    "Avenya",
    "Avevi",
    "Aveyime",
    "Avume",
    "Awate Todzi",
    "Baika",
    "Bakpa",
    "Bakpa Avedo",
    "Bame",
    "Battor",
    "Battor-Dugame",
    "Batume Junction",
    "Benua",
    "Biakpa",
    "Bleamezado",
    "Blekusu",
    "Botoku",
    "Chebi",
    "Dabala",
    "Dafor",
    "Dakpa",
    "Dayinu",
    "Dedukope",
    "Dekpoe",
    "Dekpor",
    "Dendo",
    "Denu",
    "Deve",
    "Duta",
    "Dzake",
    "Dzakpo",
    "Dzelukope",
    "Dzigbe",
    "Dzita",
    "Dzodze",
    "Dzodze Fiagbedu",
    "Dzogbe",
    "Dzogbefeme",
    "Dzogbove",
    "Dzolo Gbogame",
    "Dzolokpuita",
    "Dzorkpe",
    "Ehi",
    "Fakpoe",
    "Fanchirinko",
    "Fantekope",
    "Fesi",
    "Fiafe",
    "Fiaxor",
    "Fieve",
    "Fodome Xelu",
    "Fume",
    "Galotse",
    "Gbadzeme",
    "Gbedzekope",
    "Gbefi Hoeme",
    "Gbi Wegbe",
    "Gbota",
    "Gboxome",
    "Gefia",
    "Glidzi",
    "Glime",
    "Gonu",
    "Goviefe Agordome",
    "Goviefe Kowu",
    "Goviefe Todzi",
    "Gowenu",
    "Gui",
    "Haglakope",
    "Hatorgodo",
    "Hatsukope",
    "Have Etoe",
    "Hedzranawo",
    "Helekpe",
    "Hlefi Todome",
    "HO",
    "Hodzoga",
    "Hohoe",
    "Honuta",
    "Juapong",
    "Kakadedzi",
    "Kedzi",
    "Keta",
    "Klave",
    "Klikor",
    "Kluma",
    "Kodzi",
    "Korvenu",
    "Kpale Xorse",
    "Kpalime Duga",
    "Kpando",
    "Kpedze",
    "Kpenoe",
    "Kpenu",
    "Kpetoe",
    "Kpetonu",
    "Kpetsu",
    "Kpeve",
    "Kpevi",
    "Kpogadzi",
    "Kpoglo",
    "Kpotame",
    "Kudzra",
    "Kuli",
    "Kutime",
    "Kuve",
    "Kwanta",
    "Lave",
    "Leklebi Duga",
    "Liati Wote",
    "Likpe Bakwa",
    "Likpe Bala",
    "Likpe Koforidua",
    "Likpe Kukurantumi",
    "Likpe Mate",
    "Likpe Todome",
    "Logba Alakpeti",
    "Logba Tota",
    "Lolobi Hunyeasem",
    "Lolobi Kumasi",
    "Lume Atsyame",
    "Luta",
    "Mafi Dugame",
    "Mafi Kpedzeglo",
    "Matse Tsife",
    "Mepe",
    "Metsrikasa",
    "Nogokpo",
    "Nogopi",
    "Nyagbo Agodome",
    "Nyagbo Anyigbe",
    "Nyagbo Fiafe",
    "Nyagbo Gagbefe",
    "Nyagbo Konda",
    "Nyagbo Odumase",
    "Nyive",
    "Peki Avetile",
    "Peki Blengo",
    "Peki Wudome",
    "Penyi",
    "Pore",
    "Santrokofi Gbodome",
    "Sasekpe",
    "Savalu",
    "Saviefe Agorkpo",
    "Saviefe Gbogame",
    "Shia",
    "Sogakope",
    "Sokladzi",
    "Sokode Bagble",
    "Sokode Etoe",
    "Sokpoe",
    "Sonume",
    "Sonuto",
    "Sota",
    "Sovie",
    "Srogboe",
    "Suipe (Akatsi)",
    "Suipe (Keta)",
    "Tadzewu",
    "Tafi Abuife",
    "Tafi Agome",
    "Tafi Atome",
    "Takla",
    "Tefle",
    "Tegbi",
    "Terafomi",
    "Teti",
    "Todome Kpalime",
    "Toh Kpalime",
    "Tokokoe Abudi",
    "Tokor",
    "Tongo",
    "Tongor Kaira",
    "Tordzinu",
    "Torve",
    "Tregui",
    "Tsate",
    "Tsiame",
    "Tsito",
    "Vane",
    "Ve Agbome",
    "Ve Deme",
    "Ve Golokuati",
    "Ve Koloenu",
    "Venu",
    "Viepe",
    "Vodza",
    "Vojan",
    "Volo",
    "Volu",
    "Vume",
    "Vumenu",
    "Waya",
    "Wayanu",
    "Wegbe Kpalime",
    "Wheta",
    "Wli Afegame",
    "Wodome",
    "Wodze",
    "Woe",
    "Wowekofe",
    "Wudese",
    "Wuinta",
    "Wulite",
    "Wusuta",
    "Wusuta Resettlement",
    "Wute",
    "Wuti",
    "Xavi",
    "Yame",
    "Yordannu",
    "Yorkutikpo",
    "Ziope",
    "Zomayi (Ketu)",
    "Zomayi (Tongu)",
    "Zongo",
  ]),
  (Western = [
    "Abase-Tumentu",
    "Abetemasu",
    "Aboadze",
    "Abontiakoon",
    "Aboso",
    "Abreshia",
    "Abrokyire Krobo",
    "Abuesi",
    "Abura",
    "Achichire",
    "Achonwa",
    "Adakope",
    "Adaamanso",
    "Adamanso",
    "Adansi",
    "Adiembra (WA)",
    "Adiembra (ST)",
    "Adjua",
    "Adjumako",
    "Adubrim",
    "Adum Banso",
    "Adum Dominase",
    "Adusuazo",
    "Afransie",
    "Afrapokrom",
    "Afrebo",
    "Agona",
    "Agona Amenfi",
    "Agona Nkwanta",
    "Aguafo",
    "Agyan",
    "Agyeza",
    "Ahanko",
    "Ahobre No.1",
    "Ahobre No.2",
    "Ahwitieso",
    "Aiyinase",
    "Ajakamanso",
    "Ajomoro Eshiem",
    "Akatakyi",
    "Aketenkyen",
    "Akoko Camp",
    "Akokobediaburo",
    "Akontansi",
    "Akonu (Nzema East)",
    "Akoriso",
    "Akropong",
    "Akusuno",
    "Akutuase",
    "Akwidaa",
    "Akyempim",
    "Akyenim",
    "Akyim",
    "Alawuri",
    "Allengenzulley",
    "Amanful",
    "Amape",
    "Amoaku",
    "Amokwawsuazo",
    "Ampain",
    "Ampansie",
    "Amuni",
    "Anaji",
    "Angu",
    "Aniben",
    "Anindini",
    "Ankasa",
    "Ankasie",
    "Ankobra Junction Station",
    "Ankwaso",
    "Anlomatuope",
    "Anokyi",
    "Antseambua",
    "Apatem",
    "Apemanim",
    "Apewosika",
    "Apolonu",
    "Apowa",
    "Apremeso",
    "Arobaso",
    "Asani",
    "Asankragwa",
    "Asankran Breman",
    "Asanta",
    "Asantiaiyo",
    "Asasetre (Wassa Amenfi)",
    "Asasetre (Ellembele)",
    "Asawku",
    "Asemasa",
    "Asemko (Ahanta)",
    "Asemko (Ellembele)",
    "Aserowedi",
    "Asikafoambantem",
    "Asubey",
    "Asunti",
    "Asuogya Krobo",
    "Atasi",
    "Ateiku",
    "Atobiasi",
    "Atobiasi",
    "Atuabo",
    "Atwebanso",
    "Atwereboanda",
    "Awiabo",
    "Awolezo",
    "Awudua",
    "Awudua Nkwanta",
    "Awuku",
    "Axim",
    "Ayawora",
    "Ayiem",
    "Azuleloanu",
    "Azuleti",
    "Bakaekyir",
    "Bakanta",
    "Baku",
    "Bamiankor",
    "Banso",
    "Bawdie",
    "Benso",
    "Bepoh",
    "Beposo",
    "Beyin",
    "Bisaaso",
    "Bisakrom Jedua",
    "Bobowasi Island",
    "Bobrama",
    "Boekrom",
    "Bogoso",
    "Bompieso",
    "Bonsa",
    "Bonsa Abawye",
    "Bonsaso",
    "Bonsawire",
    "Bonyere",
    "Botogyina",
    "Bou",
    "Brofoyedru",
    "Brunikrom",
    "Busua",
    "Butre",
    "Cape Three Point",
    "Chiranam",
    "Da",
    "Daboase",
    "Dadwen",
    "Damang",
    "Dixcove",
    "Domiabra",
    "Dominase",
    "Dompim",
    "Dompim No.1",
    "Dompoase",
    "Domunli",
    "Dumase",
    "Dunkwa",
    "Duwurampong",
    "Dwenase",
    "Ebin",
    "Ebonloa",
    "Edobo",
    "Efasu",
    "Effia Nkwanta",
    "Efuanta",
    "Egbazo",
    "Egyambra",
    "Eikwe",
    "Ekabaku",
    "Ekoasi",
    "Ekpu",
    "Ellenda",
    "Ellenda Wharf",
    "Ellonyi",
    "Elubo",
    "Enyinabrim",
    "Epieso",
    "Esambolo",
    "Eshiem",
    "Esiama",
    "Essaman",
    "Essamang",
    "Essikadu",
    "Esuoso",
    "Esuowa",
    "Etinasi",
    "Ewusiejoe",
    "Ezinlibo",
    "Fanti Village",
    "Fasin",
    "Fawomanye",
    "Fijai",
    "Furabawye",
    "Fure",
    "Fweyiye",
    "Gwira Banso",
    "Gwira Eshiem",
    "Gyama",
    "Gyedua Kese",
    "Gyimakrom",
    "Half Assini",
    "Hianye",
    "Hiawa",
    "Himakrom",
    "Himan",
    "Huni Valley",
    "Huniabawye",
    "Huniano Nos. 1 & 2",
    "Huniso",
    "Hyedua",
    "Inchaban",
    "Insu",
    "Japa",
    "Jaway",
    "Jaway Wharf",
    "Juabo",
    "Jukwa",
    "Kabenlasuazo",
    "Kamgbunli",
    "Kansawurado",
    "Kanyankaw",
    "Kejabil",
    "Ketiboa Blay Village",
    "Kengen",
    "Kikam",
    "Kojokrom",
    "Kokum",
    "Komfueku",
    "Krisan",
    "Kuranti",
    "Kutukrom",
    "Kwabeng",
    "Kwamang",
    "Kwameniampa",
    "Kwasikrom",
    "Kyekyewere",
    "Kwesimintsim",
    "Mampong",
    "Mangyea",
    "Manso",
    "Manso Amenfi",
    "Mbeasi-Nsuta",
    "Miegyinla",
    "Miemia",
    "Moseaso",
    "Mpasem",
    "Mpataba",
    "Mpeasem",
    "Mpem",
    "Mpohor",
    "Nananko",
    "Nawuley",
    "Nduam",
    "New Subri",
    "Newtown",
    "Ngalekyi",
    "Ngalekpole",
    "Ngelekazo",
    "Ngyiresia",
    "Nkonsia",
    "Nkontompo",
    "Nkrang",
    "Nkroful",
    "Nkwanta (TN)",
    "Nkwanta (WAC)",
    "Nkwanta (WAW)",
    "Nsuaem",
    "Nsuaem No.1",
    "Nsuaem (Nzema)",
    "Nsuta (Tarkwa)",
    "Nsuta (Wassa)",
    "Nuba",
    "Nyametease",
    "Nyankumase",
    "Nyanso",
    "Nzematianu",
    "Nzulezo",
    "Obinyimkyena",
    "Odumase",
    "Ohiamadwen",
    "Opon Valley",
    "Oponsokese",
    "Pepesa",
    "Peterkrom",
    "Prestea",
    "Princess Town",
    "Punpuni",
    "Salman",
    "Saamang",
    "Samenye",
    "Samreboi",
    "Saa",
    "Sanwoma",
    "Saponso",
    "Sekyere Himan",
    "Sekyere Krobo",
    "Sekyere Obuase",
    "Sraha",
    "Sekondi",
    "SEKONDI-TAKORADI",
    "Sese",
    "Shama",
    "Sikaneasem",
    "Simpa",
    "Subri",
    "Suffer To Gain",
    "Suhyenso",
    "Takinta",
    "Takoradi",
    "Tamso",
    "Tanoso",
    "Tarkwa",
    "Tarkwa Breman",
    "Tetrem",
    "Tikobo No.1",
    "Tikobo No.2",
    "Tumentu",
    "Twenen",
    "Wassa Akropong",
    "Wassa Bekwai",
    "Wassa Dompim",
    "Wassa Nkran",
    "Whindo",
    "Woman No Good",
    "Yabiw",
    "Yirase",
  ]),
  (Western_North = [
    "Aboduam",
    "Abokyia",
    "Achimfo",
    "Ackaakrom",
    "Adabokrom",
    "Adiembra",
    "Adiepena",
    "Adjoafua",
    "Adonikrom",
    "Adupri",
    "Afere",
    "Agyemandiem",
    "Ahibenso",
    "Ahimakrom",
    "Ajum",
    "Akontombra",
    "Amafie",
    "Amoaya",
    "Ampeni",
    "Anhwiaa",
    "Anhwiam",
    "Anhwiaso",
    "Ankunso",
    "Anokokrom",
    "Antobia",
    "Aquai Allah",
    "Asafo",
    "Asamang",
    "Asawinso",
    "Asemkrom",
    "Ashiem",
    "Asuontaa",
    "Atokosue",
    "Atuakrom",
    "Awaso",
    "Ayeboso",
    "Benchema",
    "Benomsuo",
    "Biano",
    "Bibiani",
    "Bodi",
    "Boinso",
    "Boinzan",
    "Bokaso",
    "Bopa",
    "Buako",
    "Buako Nkwanta",
    "Camp",
    "Chirano",
    "Dadieso",
    "Datano",
    "Debiso",
    "Debiso (Old)",
    "Disuaboi",
    "Disueano",
    "Domi",
    "Dominibo No.1",
    "Duwakrom",
    "Elluokrom",
    "Enchi",
    "Essam",
    "Eteso",
    "Fahiakobo",
    "Huitimbo",
    "Humjibre",
    "Jema",
    "Jomoro",
    "Juaboso",
    "Kama",
    "Karlo",
    "Kobo",
    "Kofikrom",
    "Kojina",
    "Kojokrom",
    "Kramokrom",
    "Krokosue",
    "Kwabenakrom",
    "Kwamebikrom",
    "Kwametawiakrom",
    "Kwasare",
    "Kwasikrom",
    "Kwawu",
    "Kyekyewere",
    "Mafia",
    "Manse",
    "Mesrenyame",
    "Mpesiem",
    "Nkatieso",
    "Nkronua Atifi",
    "Nkwadum",
    "Nsinsem",
    "Nsonyameye",
    "Nsuonsua",
    "Nyamennae",
    "Nyankoman",
    "Ohiayeanisa",
    "Omanpe",
    "Oseikojokrom",
    "Patakro",
    "Sayerano",
    "Sayeraso",
    "Sefwi Bekwai",
    "SEFWI WIAWSO",
    "Sewum",
    "Subri",
    "Subri Nkwanta",
    "Sui",
    "Suiano",
    "Surano",
    "Wenchi",
    "Yakasi",
    "Yamaso",
    "Yawmatwa",
  ]),
];
